#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kazuha Mogi <mogi2fruits.kazu@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys

unsorted_list = []
R = 1.0 # クラスタの半径

# 入力データのクリーンアップ
try:
	for line in sys.stdin:
		# 入力をfloat型に変換しリストに追加
		floline = float(line.strip())
		unsorted_list.append(floline)
except ValueError:
	sys.exit(1)

sorted_list = sorted(unsorted_list)

# クラスタに関する処理
clusters_count = 0
i = 0 
n = len(sorted_list)
while i < n:	 
	clusters_count += 1
	clrange = sorted_list[i] + 2.0 * R # inf[C-R, C+R]=sorted_list[i]として左の範囲で値を収められれば良い．
	while i < n and sorted_list[i] <= clrange:
		i += 1
		
print(clusters_count)
	 

	
	
