#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Kazuha Mogi <mogi2fruits.kazu@gmail.com>
# SPDX-License-Identifier: BSD-3-Clause

import sys

unsorted_list = []
for line in sys.stdin:
	floline = float(line)
	unsorted_list.append(floline)

print(unsorted_list)
	
